#ifndef QUERYLENS_PLANNER_HPP
#define QUERYLENS_PLANNER_HPP

#include "parser.hpp"
#include <string>

namespace querylens {

// Execution method chosen by the query planner
enum class ExecutionMethod {
    SEQUENTIAL_SCAN,
    SEGMENT_TREE,
    LAZY_SEGMENT_TREE,
    FENWICK_TREE,
    BPLUS_TREE
};

// Query execution plan generated by the planner
struct QueryPlan {
    ParsedQuery query;
    ExecutionMethod method;
    std::string explanation;

    std::string methodToString() const;
    std::string toJSON() const;
};

// Query planner: selects the best execution method
class QueryPlanner {
public:
    // Automatically choose best method based on query type
    static QueryPlan plan(const ParsedQuery& query, bool has_segment_tree = true,
                          bool has_fenwick = true, bool has_bplus = true);

    // Force a specific execution method
    static QueryPlan planWith(const ParsedQuery& query, ExecutionMethod method);
};

} // namespace querylens

#endif // QUERYLENS_PLANNER_HPP
